//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investomania.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int Id { get; set; }
        public string newsTitle { get; set; }
        public string newsContent { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
